### ISSUE TITLE
State positions are emptied - onCandleUpdate returns the initial state instead of the updated state

### ISSUE THREAD

**Issue by Lecss** [bitfinexcom/bfx-hf-strategy#9]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
This bug can be seen on using live data stream, with the bfx-hf-strategy-exec. When a new candle is received, upon processing the candle update message and a trade is executed, the state position object is overridden by the previous empty positions state; 

#### Steps to reproduce
-  run with bfx-hf-strategy-exec, place a trade from either onUpdate or onEnter. Position state is updated temporarily,  then on next candle_update it is reverted to empty object;

**Comment by f3rno** [comment]
This should have been fixed by https://github.com/bitfinexcom/bfx-hf-backtest/commit/e3c7bc7ebc1284b96654080868c7098263fd55ca @Lecss can you confirm?

**Comment by Lecss** [comment]
This issue was related to bfx-hf-strategy on_candle_update not returning the new state ( this is now merged in this repo) . You might want to double check but I don't see it being related to bitfinexcom/bfx-hf-backtest@e3c7bc7. Also I encountered it while using bfx-hf-strategy-exec which doesn't seem to have bfx-hf-backtest as dependecy.

**Comment by JacobPlaster** [comment]
Yeah @Lecss already fixed the issue in https://github.com/bitfinexcom/bfx-hf-strategy/pull/10. Thanks!
